language: node_js
env:
  matrix:
    - "BROWSER='firefox::Windows 10'"
    - "BROWSER='chrome::Windows 10'"
    #- "BROWSER='MicrosoftEdge:14.14393:Windows 10'"
    #- "BROWSER='internet explorer:11.103:Windows 10'"
    #- "BROWSER='safari:10.0:macOS 10.12'"
    #- "BROWSER='safari:9.0:OS X 10.11'"
branches:
  only:
    - master
    - soon
    - staging
node_js:
  - "6.6.0"
before_script:
  - npm run-script lint
  - npm run-script flow
  - cp config.example.js config.js
  - npm install bower
  - ./node_modules/bower/bin/bower install
  - node ./server.js &
  - sleep 2
